import { Kysely, PostgresDialect } from "kysely";
import { Pool } from "pg";
import { DB } from "@/types/db-types"; // This will be generated by prisma-kysely

const dialect = new PostgresDialect({
	pool: new Pool({
		connectionString: process.env.DATABASE_URL,
		max: 10,
	}),
});

// Database interface is generated from prisma schema
export const db = new Kysely<DB>({
	dialect,
});
